"""empty message

Revision ID: 1ea6cbf258d6
Revises: 6399b8d560bc
Create Date: 2020-08-02 18:20:29.957353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea6cbf258d6'
down_revision = '6399b8d560bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'image')
    # ### end Alembic commands ###
